version: '3'

services:

  mongodb:
    image: "mongo:4.0.6"
    ports:
      - "27017:27017"
    command: mongod --smallfiles


  test-api:
    build: ./test-api
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      MONGODB_SERVER: mongodb
